config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'

  #create password routes
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'

  #signup routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  #signin routes
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  #create password reset route
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  #create edit password routes
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  #create twitter omniauth routes
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  delete 'logout', to: 'sessions#destroy'

  resources :twitter_accounts
  resources :tweets
  
  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :published_at, presence: true

  after_initialize do
    self.published_at ||= 24.hours.from_now
  end

  after_save_commit do
    if published_at_previously_changed?
      TweetJob.set(wait_until: published_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy
  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Invalid email address' }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user
	
    def set_current_user
		if session[:user_id]
			Current.user = User.find_by(id: session[:user_id])
		end
    end

	def require_user_logged_in!
		redirect_to sign_in_path, alert: "You must be logged in to access this page." if Current.user.nil? 	
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

  def twitter    
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    
    twitter_account.update(
        name: auth.info.name,
        username: auth.info.nickname,
        image: auth.info.image,
        token: auth.credentials.token,
        secret: auth.credentials.secret  
    )

    redirect_to twitter_accounts_path, notice: 'Twitter account added'
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end
  
  def create
    @user = User.find_by_email(params[:email])

    if @user.present?
        #send email
        PasswordMailer.with(user: @user).reset.deliver_now
    end

    redirect_to root_path ,notice: "Instructions to reset your password have been sent to your email."    
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')

    rescue  ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Please request a new one."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
        redirect_to sign_in_path, notice: "Your password has been updated."
    else
        render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
#create password controller
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    
    def edit

    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated"
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successful Signup"      
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
      
   end

   def create
      user = User.find_by(email: params[:email])
      if user.present? && user.authenticate(params[:password])
         session[:user_id] = user.id
         redirect_to root_path, notice: "Logged In Successfully"
      else
         flash[:alert] = "Invalid email or password"
         render :new
      end
   end

   def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged Out"
   end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:edit, :update, :destroy, :show]

  def index
    @tweets = Current.user.tweets
  end
  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      TweetJob.set(wait_until: @tweet.published_at).perform_later(@tweet)
      redirect_to tweets_path, noice: "Tweet was scheduled!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      TweetJob.set(wait_until: @tweet.published_at).perform_later(@tweet)
      redirect_to tweets_path, notice: "Tweet was updated!"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was deleted!"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end
  
  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path, notice: "Twitter account #{@twitter_account.name} deleted."
  end
  
  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="min-h-screen bg-gray-100">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <div class="grid mx-auto flex justify-center	pt-6 place-content-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Home Page for Tweets</h1>

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"  %>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form|  %>
        <% if form.object.errors.any? %>
            <div class="text-red-500 text-xs italic">
                <% form.object.errors.full_messages.each do |message| %>
                    <p><%= message %></p>
                <% end %>
            </div>
        <% end %>
        <div class="mb-4">
            <%= form.password_field :password, placeholder: "Password", class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        </div>
        <div class="mb-4">
            <%= form.password_field :password_confirmation, placeholder: "Confirm Password",  class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        </div>
        <div class="mb-4">
            <%= form.submit "Reset Password", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>        
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>

<%= form_with url: password_reset_path do |form|  %>
        <div class="mb-4">
            <%= form.text_field :email, placeholder: "Email", class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        </div>    
        <div class="mb-4">
            <%= form.submit "Reset Password", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>        
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

<div class="bg-green-200 border-green-600 text-green-600 border-l-4 p-4" role="alert">
    <p class="font-bold">
        Success
    </p>
    <p>
    <%= flash[:notice].inspect %>
    </p>
    
</div>
<% end %>

<% if flash[:alert] %>
<div class="bg-red-200 border-red-600 text-red-600 border-l-4 p-4" role="alert">
    <p class="font-bold">
        Alert
    </p>
    <p>
        <%= flash[:alert] %>
    </p>
</div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
<div class="text-red-500 text-xs italic">
    <% form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <% end %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div>
    <nav class="bg-white dark:bg-gray-800  shadow py-4 ">
        <div class="max-w-7xl mx-auto px-8">
            <div class="flex items-center justify-between h-16">
                <div class=" flex items-center">
                    <a class="flex-shrink-0" href="/">
                        <h2 class="font-bold text-yellow-500	 text-4xl">Tweets</h2>
                    </a>
                    <div class="">
                        <div class="ml-10 flex items-baseline space-x-4">
                            <%= link_to "Home", root_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>
                            <%= link_to "Tweets", tweets_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>
                            
                            <%= link_to "About", about_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>
                            <%= link_to "Twitter Accounts", twitter_accounts_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>                            
                        <% if Current.user %>
                            <%= link_to Current.user.email, edit_password_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>
                            <%= button_to "Logout", logout_path, method: :delete, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
                        <% else %>
                            <%= link_to "Login", sign_in_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>
                            <%= link_to "Sign Up", sign_up_path, class: "text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-md font-medium" %>
                        <% end %>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </nav>
</div>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
    <%= render "shared/form_errors", form: form %>
    <div class="mb-3">
        <%= form.label :twitter_account_id %>
        <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: 'block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline'} %>
        <%= link_to "Connect Another Twitter Account", "/auth/twitter", class: 'font-bold hover:text-red' %>
    </div>
    <div class="mb-3">
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>    
    <div class="mb-3">
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at %>
    </div>        
    <div class="mb-3">
        <%= form.button "Schedule Tweet", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
    <div class="mb-3">
    <% if form.object.persisted? %>
        <%= link_to "Delete Tweet", form.object, method: :delete, data: { confirm: "Are you sure?"},  class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    <% end %>
    </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
    <%= tweet.body %>
    <div class="mb-4">
        <%= image_tag tweet.twitter_account.image, class: '' %>
        <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank%>
        <%= button_to "Disconnect", tweet.twitter_account, method: :delete, data: { confirm: "Are you sure?"} %>        
    </div>
    <div class="mb-4">
        <% if tweet.published? %>
          <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}/" ,target: :_blank %>
        <% else %>
            Scheduled for: <%= l tweet.published_at, format: :long %>
            <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
        <% end %>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<div class="max-w-sm rounded overflow-hidden shadow-lg">
    <div class="px-6 pt-4 pb-2">
    <% if Current.user.twitter_accounts.any? %>
        <%= link_to "Schedule a Tweet", new_tweet_path, class: 'bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded' %>
    <% end %>
    </div>
</div>

<div class="max-w-sm rounded overflow-hidden shadow-lg">
    <div class="px-6 pt-4 pb-2">
    <% if Current.user.twitter_accounts.none? %>
        <%= link_to "Connect Your Twitter Account", "/auth/twitter", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded' %>
    <% end %>
    </div>
</div>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet</h1>

<%= form_with model: @tweet do |form| %>
    <%= render "shared/form_errors", form: form %>
    <div class="mb-3">
        <%= form.label :twitter_account_id %>
        <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: 'block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline'} %>
        <%= link_to "Connect Another Twitter Account", "/auth/twitter", class: 'font-bold hover:text-red' %>
    </div>
    <div class="mb-3">
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>    
    <div class="mb-3">
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at %>
    </div>        
    <div class="mb-3">
        <%= form.button "Schedule Tweet", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
<% end %>

app/views/twitter_accounts/index.html.erb
<h1 class="place-content-center	mb-5">Twitter Accounts</h1>

<%= link_to 'Connect Twitter Account', '/auth/twitter', method: :post, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>

<div class="place-content-center	">
	<% @twitter_accounts.each do |twitter_account| %>
		<div class="mt-5">
			<%= image_tag twitter_account.image, class: '' %>
			<%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank%>
			<%= button_to "Disconnect", twitter_account, method: :delete, data: { confirm: "Are you sure?"} %>
		</div>
	<% end %>
</div>